test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y tidy
    - tidy -e index.html second.html

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - master
  dependencies:
    - test

