stages:
  - test
  - deploy
  - clone_and_push

validate_html:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y tidy
    - tidy -e index.html second.html

deploy_html:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main

clone_and_push:
  stage: clone_and_push
  script:
    - git clone https://gitlab.com/desmondlch/mytest.git
    - cd mytest
    - git remote set-url origin https://github.com/desmondlch/FinalProject2.git
    - git push origin master


