stages:
  - test
  - deploy
  - update_github

validate_html:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y tidy
    - tidy -e index.html second.html

deploy_html:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main

update_github:
  stage: update_github
  script:
    - git clone https://github.com/desmondlch/FinalProject2.git
    - cd your-github-repo
    - git config --global user.email "desmondleongch@gmail.com"
    - git config --global user.name "Desmond"
    - git checkout main  # or the branch you want to update
    - git pull https://oauth2:${GITHUB_TOKEN}@github.com/your-username/your-github-repo.git
    - git push origin main  # or the branch you want to update
  only:
    - main  # or specify the branches you want to trigger the update


