stages:
  - test
  - deploy
  - push_to_github

validate_html:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y tidy
    - tidy -e index.html second.html

deploy_html:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main

variables:
  GITHUB_REPO_URL: "https://github.com/desmondlch/FinalProject3.git"

push_to_github:
  stage: push_to_github
  script:
    - git clone https://gitlab.com/desmondlch/mytest.git
    - cd mytest
    - git remote set-url --push origin $GITHUB_REPO_URL
    - git push origin main



