stages:
  - test
  - deploy
  - update_github

validate_html:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y tidy
    - tidy -e index.html second.html

deploy_html:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main

update_github:
  stage: update_github
  script:
    - git clone https://gitlab.com/desmondlch/mytest.git
    - cd MyTest
    - git remote set-url origin https://github.com/desmondlch/FinalProject2.git
    - git push origin main
  only:
    - main  # Run this job only when changes are pushed to the master branch



