stages:
  - test
  - deploy

validate_html:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y tidy
    - tidy -e index.html second.html

deploy_html:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main

